### ISSUE TITLE
Dispenseren skal fungere funktionelt uden anden brugergrænseflade.

### ISSUE THREAD

**Issue by Webfusiondk** [H4-Medicine-Team/SmartDispenser#12]
## Accept kriterier
- Dispenseren skal have egen brugergrænseflade
- Dispenseren skal kunne navigere sig på brugergrænsefladen ved brug af touch 

## Tasks
- [x] Installation af raylib
- [x] Integration med touch
- [x] Basic proof of gui concept
- [x] Dokumentation
