### ISSUE TITLE
Dispenseren skal holde styr på medicinkort.

### ISSUE THREAD

**Issue by Webfusiondk** [H4-Medicine-Team/SmartDispenser#15]
## Accept kriterier
- Dispenseren skal display Medicinkort på UI
- Ved brug af display skal man kunne redigere/tilføje præparater til medicinkort
- Gemme medicinkort i lokal databasen
- Hente Medicinkort fra lokal databasen

## Tasks
- [x] Lav ui for visning af medicinkort
- [x] Tilføj præperat til medicinkort
- [x] Rediger præperat i medicinkort
- [x] Slet præperat fra medicinkort
- [x] Gem medicinkort fra lokal database
- [x] Hent medicinkort fra lokalt database
- [x] Dokumentation
- [x] Tests
